name: Xeneta Scraper

on:
  push:
    branches:
      - main
  schedule:
    # 每天凌晨 0 点 UTC 时间运行
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run_scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pygsheets requests pandas retrying

      - name: Run Xeneta Scraper
        run: python Xeneta_Scraper.py
        env:
          # 将你的用户名和密码作为 GitHub Secrets，以确保安全
          # 在你的 GitHub 项目设置中创建名为 XENETA_USERNAME 和 XENETA_PASSWORD 的秘密
          XENETA_USERNAME: ${{ secrets.XENETA_USERNAME }}
          XENETA_PASSWORD: ${{ secrets.XENETA_PASSWORD }}

      - name: Upload downloaded files
        uses: actions/upload-artifact@v4
        with:
          name: xeneta-data
          path: /content
