name: Xeneta Scraper

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scrape_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas pygsheets requests openpyxl
          
      - name: Create temporary downloads directory
        run: |
          mkdir -p /tmp # Ensure this matches DOWNLOAD_DIR in your Python script

      - name: Create service account key file
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "$GCP_SA_KEY" > /tmp/service_account_key.json

      - name: Run Xeneta Scraper
        env:
          XENETA_USERNAME: ${{ secrets.XENETA_USERNAME }}
          XENETA_PASSWORD: ${{ secrets.XENETA_PASSWORD }}
        run: |
          python Xeneta_Scraper.py
